const PORT = 8082;
const NEW_AUCTION_EXPIRATION = 20000
const BIDDER_WINS_AFTER = 7000
const MIN_USERS_FOR_AUCTION = 2

module.exports = { PORT, NEW_AUCTION_EXPIRATION, BIDDER_WINS_AFTER, MIN_USERS_FOR_AUCTION };
